"""Train a guarded first baseline for employee risk classification.

This module deliberately skips training when the cleaned employee dataset does
not contain enough real employee rows and independent labels. It never treats
Kaggle email rows as employee records and never promotes heuristic
RiskAssessment output to a ground-truth label.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASET = ROOT / "ml" / "data" / "processed" / "employee_features.csv"
DEFAULT_REPORT = ROOT / "ml" / "data" / "processed" / "training_report.json"
DEFAULT_MODEL_DIR = ROOT / "ml" / "models"
DEFAULT_MODEL = DEFAULT_MODEL_DIR / "risk_model.joblib"
TARGET_COLUMN = "risk_label"
RISK_CLASSES = ["Low", "Medium", "High"]
MIN_SAMPLES = 30
MIN_SAMPLES_PER_CLASS = 5
TEST_SIZE = 0.2

# These are generated by the prototype formula and must not become model inputs.
NON_FEATURE_COLUMNS = {
    "employee_id",
    TARGET_COLUMN,
    "heuristic_risk_assessment_available",
    "heuristic_final_risk_score",
    "heuristic_risk_level",
}


def choose_classifier() -> Pipeline:
    """Return the replaceable baseline classifier configuration.

    baseline — subject to change
    """
    # baseline — subject to change; swap this pipeline implementation when a better model is selected.
    return Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            (
                "classifier",
                LogisticRegression(
                    max_iter=1000,
                    class_weight="balanced",
                    random_state=42,
                ),
            ),
        ]
    )


def class_distribution(dataframe: pd.DataFrame) -> dict[str, int]:
    if TARGET_COLUMN not in dataframe:
        return {}
    return {
        str(label): int(count)
        for label, count in dataframe[TARGET_COLUMN].value_counts(dropna=False).items()
    }


def skip_report(
    dataframe: pd.DataFrame,
    reasons: list[str],
) -> dict[str, Any]:
    valid_labels = (
        dataframe[TARGET_COLUMN]
        .astype("string")
        .str.strip()
        .isin(RISK_CLASSES)
        .sum()
        if TARGET_COLUMN in dataframe.columns
        else 0
    )
    return {
        "training_performed": False,
        "employee_samples_available": len(dataframe),
        "independent_labels_available": int(valid_labels),
        "samples_used": 0,
        "number_of_classes": 0,
        "class_distribution": class_distribution(dataframe),
        "accuracy": None,
        "confusion_matrix": None,
        "classification_report": None,
        "reasons": reasons,
        "target_column": TARGET_COLUMN,
        "heuristic_labels_used": False,
    }


def validate_training_data(dataframe: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    """Validate independent labels and split prerequisites before fitting."""
    reasons: list[str] = []
    if TARGET_COLUMN not in dataframe.columns:
        reasons.append(
            "No independent risk_label column exists. heuristic_risk_level is not used "
            "because RiskAssessment values are heuristic, not ground truth."
        )
        return dataframe.iloc[0:0], reasons

    labelled = dataframe.copy()
    labelled[TARGET_COLUMN] = labelled[TARGET_COLUMN].astype("string").str.strip()
    labelled = labelled[labelled[TARGET_COLUMN].isin(RISK_CLASSES)].copy()
    if len(labelled) < len(dataframe):
        reasons.append("Rows with missing or invalid labels were excluded.")

    distribution = class_distribution(labelled)
    if len(labelled) < MIN_SAMPLES:
        reasons.append(
            f"Only {len(labelled)} valid labelled employees are available; "
            f"at least {MIN_SAMPLES} are required for this baseline."
        )
    if len(distribution) < 2:
        reasons.append("At least two risk classes are required for classification.")
    if distribution and min(distribution.values()) < MIN_SAMPLES_PER_CLASS:
        reasons.append(
            f"Each class needs at least {MIN_SAMPLES_PER_CLASS} employees for a meaningful split; "
            f"current distribution is {distribution}."
        )
    return labelled, reasons


def build_preprocessor(features: pd.DataFrame) -> ColumnTransformer:
    features = features.copy()
    for column in features.select_dtypes(include="bool").columns:
        features[column] = features[column].astype("int8")

    numeric_columns = features.select_dtypes(include="number").columns.tolist()
    categorical_columns = features.select_dtypes(exclude="number").columns.tolist()
    transformers: list[tuple[str, Any, list[str]]] = []
    if numeric_columns:
        transformers.append(
            (
                "numeric",
                Pipeline([("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]),
                numeric_columns,
            )
        )
    if categorical_columns:
        transformers.append(
            (
                "categorical",
                Pipeline(
                    [
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        ("onehot", OneHotEncoder(handle_unknown="ignore")),
                    ]
                ),
                categorical_columns,
            )
        )
    return ColumnTransformer(transformers=transformers)


def train_and_evaluate(dataframe: pd.DataFrame) -> tuple[Pipeline, dict[str, Any]]:
    labelled, reasons = validate_training_data(dataframe)
    if reasons:
        raise ValueError("Training skipped: " + " ".join(reasons))

    features = labelled.drop(columns=list(NON_FEATURE_COLUMNS & set(labelled.columns)))
    labels = labelled[TARGET_COLUMN]
    x_train, x_test, y_train, y_test = train_test_split(
        features,
        labels,
        test_size=TEST_SIZE,
        random_state=42,
        stratify=labels,
    )
    model = Pipeline(
        steps=[
            ("preprocessor", build_preprocessor(features)),
            ("classifier", choose_classifier()),
        ]
    )
    model.fit(x_train, y_train)
    predictions = model.predict(x_test)
    matrix = confusion_matrix(y_test, predictions, labels=RISK_CLASSES)
    report = classification_report(
        y_test,
        predictions,
        labels=RISK_CLASSES,
        target_names=RISK_CLASSES,
        output_dict=True,
        zero_division=0,
    )
    return model, {
        "training_performed": True,
        "employee_samples_available": len(dataframe),
        "independent_labels_available": len(labelled),
        "samples_used": len(labelled),
        "number_of_classes": labels.nunique(),
        "class_distribution": class_distribution(labelled),
        "test_samples": len(y_test),
        "accuracy": float(accuracy_score(y_test, predictions)),
        "confusion_matrix": matrix.tolist(),
        "confusion_matrix_labels": RISK_CLASSES,
        "classification_report": report,
        "reasons": [],
        "target_column": TARGET_COLUMN,
        "heuristic_labels_used": False,
    }


def run(dataset_path: Path, report_path: Path, model_path: Path) -> dict[str, Any]:
    if not dataset_path.exists():
        report = {
            "training_performed": False,
            "dataset_path": str(dataset_path),
            "reasons": [f"Dataset not found at {dataset_path}. Build employee features before training."],
            "model_path": str(model_path),
        }
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        return report

    dataframe = pd.read_csv(dataset_path)
    model = None
    try:
        model, report = train_and_evaluate(dataframe)
    except ValueError as error:
        report = skip_report(dataframe, [str(error)])

    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    if model is not None:
        import joblib

        model_path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(model, model_path)
        report["model_path"] = str(model_path)
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    args = parser.parse_args()
    report = run(args.dataset, args.report, args.model)
    if report.get("training_performed"):
        accuracy = report.get("accuracy")
        confusion = report.get("confusion_matrix")
        print(f"Accuracy: {accuracy:.4f}" if accuracy is not None else "Accuracy: unavailable")
        print("Confusion matrix:")
        print(json.dumps(confusion, indent=2) if confusion is not None else "[]")
    else:
        print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
